export {default as Contact} from "./Contact"
export {default as Header} from "./Header"
export {default as Footer} from "./Footer"
export {default as Services} from "./Services";
export {default as Input} from "./Input";
export {default as Image} from "./Image";
export {default as Hero} from "./Hero";
export {default as Section} from "./Section";
export {default as Button} from "./Button";
export {default as Card} from "./Card";
export {default as TestimonialSlider} from "./TestimonialSlider";
export {default as ImageCarousel} from "./ImageCarousel";
export {default as GalleryComponent} from "./GalleryComponent";
export {default as MobileIcon} from "./MobileIcon";
export {default as Mobilenav} from "./Mobilenav"
export {default as HeroTitle} from "./HeroTitle"
export {default as Gradient} from "./Gradient"
export {default as Logo} from "./Logo"
export {default as Video} from "./Video"
export {default as TestimonialCard} from "./TestimonialCard"
export {default as GradientDivider} from "./GradientDivider"
export {default as Divider} from "./Divider"
export {default as CoverSection} from "./CoverSection";
export {default as Title} from "./Title";
export {default as ImageCard} from "./ImageCard";